
title: RooBot.dev
email: contact-git@roobot.dev
description: >- # this means to ignore newlines until "baseurl:"
  Coming soon.
domain: www.roobot.dev
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.roobot.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  roobot-dev

# Build settings
theme: minima
plugins:
  - jekyll-feed

